there is a non-zero chance that this could actually work on the first try

diff --git a/var/lib/xinit/functions b/var/lib/xinit/functions
--- a/var/lib/xinit/functions
+++ b/var/lib/xinit/functions
@@ -468,16 +468,52 @@ get_info ()
 
         if [ -e ${TOMCAT_HOME}/logs/catalina.out ]
                 then
-                PREKILL_LOG_NUMBER="`wc -l ${TOMCAT_HOME}/logs/catalina.out | awk '{print $1}'`"
+
+                local dumpFile=`tempfile`;
+                (
+                        tail -f ${TOMCAT_HOME}/logs/catalina.out | awk '
+                                BEGIN { counter=0; ftd=""; recording=0; }
+                                {
+                                    if ($0 ~ /^Full thread dump/) { recording=1; }
+                                    if (recording) {
+                                        if (counter) {
+                                            if (!--counter) {
+                                                print(ftd);
+                                                exit(0);
+                                            }
+                                        } else if ($0 == "Heap") {
+                                            counter=9;
+                                        }
+                                        ftd=ftd"\n"$0;
+                                    }
+                                }' | $dumpFile;
+                ) &
+                local dumpPid=$1;
+
+                (
+                    sleep 120;
+                    echo 'dump pid still running after 120 seconds, killing it' >> $ATTACHE_FILE;
+                    kill $dumpPid;
+                    sleep .1 || exit 0;
+                    kill -0 $dumpPid && exit 0;
+                    sleep 10 || exit 0;
+                    kill -0 $dumpPid && exit 0;
+                    echo 'dump pid still running after 10 more seconds, kill -9' >> $ATTACHE_FILE;
+                    kill -9 $dumpPid;
+                ) &
+                local killDumpPid=$!
+
+                #PREKILL_LOG_NUMBER="`wc -l ${TOMCAT_HOME}/logs/catalina.out | awk '{print $1}'`"
 
                 # Execute kill -QUIT
                 local java_pid="`pidof $TOMCAT_PROCESS_NAME`"
                 kill -3 $java_pid
-                sleep $KILL_QUIT_TIME_WAIT
 
-                POSTKILL_LOG_NUMBER="`wc -l ${TOMCAT_HOME}/logs/catalina.out | awk '{print $1}'`"
-                # Calculating the thread dump size.
-                KILLQUIT_LOG_LINES="$((${POSTKILL_LOG_NUMBER} - ${PREKILL_LOG_NUMBER}))"
+                wait $dumpPid
+                sleep .5; ## need long enough for killDumpPid to exit...
+                ! kill $killDumpPid && echo 'thread dump failed' >> $ATTACHE_FILE && return 0;
+
+                KILLQUIT_LOG_LINES=`cat $dumpFile`
 
 		                # Thread dump Analysis
                 if [ ! -z "$THREADDUMP_ANALYSIS" ]
